Jcn 436 fix body error overwritten
janis-commerce/lambda pull request #13
Opened 2023-06-29 18:59 UTC by calandrajose

Link al ticket

[Historia](https://janiscommerce.atlassian.net/browse/JCN-435)

[Subtarea](https://janiscommerce.atlassian.net/browse/JCN-436)

### Descripción del requerimiento

#### Contexto

Cuando una Lambda es parte de una state machine y tiene un payload que supera al tamaño permitido por AWS, se sube la informacion a un bucket de S3 y se reemplaza esa informacion por la propiedad contentS3Path .

Al iniciar el step siguiente, desde el mismo paquete se valida si existe contentS3Path. Si existe, se descarga el contenido del S3 y se reemplaza el body con el cual se inicio la ejecución.

#### Problema

Cuando una ejecución falla por errores no controlados (como puede ser una lambda fallando por Timeout) y existe un step posterior para manejo de errores, si el payload es muy grande se da el siguiente escenario:

- Falla Lambda
- Redirige al Handle error con el ultimo payload del flujo mas la propiedad error con toda la info necesaria
- Inicia ejecución del Handle Error
  - El package encuentra la prop contentS3Path
  - Descarga el payload
  - Se pisa `this.data` con lo que había en S3, perdiendose la prop `this.data.error`
  - Rompe la ejecución del HandleError

### Descripción de la solución
Se modificaron los métodos `getFullData` para que al descargar un payload de S3 tambien incluya, si es que existe, el error recibido.

### Changelog

```
### Fixed
- ***Lambda*** and ***Parallel*** Handlers deleting received error data after downloading payload from S3
```

2023-07-03 14:51 UTC, Alejandro-Gonzalez requested changes

2023-07-03 14:51 UTC, Alejandro-Gonzalez commented on lib/parallel-handler.js
> +		return Promise.all(body.map(async item => {
@calandrajose Acá podríamos usar directamente getFullData de Handler

`return Promise.all(body.map(super.getFullData));`

2023-07-03 19:06 UTC, Alejandro-Gonzalez approved these changes

2023-07-06 21:40 UTC, gastonpereyra approved these changes

2023-07-11 17:51 UTC, jormaechea requested changes
El código está OK, pero necesitamos documentarlo en el README.
La propiedad `error` es algo elegido aleatoriamente en la definición de una state machine.
![image](https://github.com/janis-commerce/lambda/assets/5612500/141eb0b9-1d6c-4695-abc6-4141b57d8d2c)

Si vamos a usarlo como estándar, hay que agregarlo a la docu.

2023-07-13 18:48 UTC, jormaechea approved these changes

2023-07-13 18:48 UTC, merged