JCN-347 invocar lambdas servicios
janis-commerce/lambda pull request #4
Opened 2022-01-17 19:43 UTC by Nataniel4

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-347

**LINK A LA HISTORIA**
https://fizzmod.atlassian.net/browse/JCN-346

**DESCRIPCIÓN DEL REQUERIMIENTO**
Sumar 4 nuevos métodos al package
- `serviceCall()`
- `serviceClientCall()`
- `serviceSafeCall()`
- `serviceClientSafeCall()`

⚠️ Estos métodos son para invocar funciones de otros servicios por lo que sera necesario asumir el rol de IAM correspondiente y generar el Partial ARN de la función

ℹ️ Además estos métodos deben responder con un objecto que tenga el `statusCode` y `payload` de respuesta de la función, para poder usarlo para pegarle a lambdas de APIs como si usáramos MicroserviceCall.

También agregar un nuevo lambda base `LambdaWithPayload`

Más detalles en la historia 😉

**DESCRIPCIÓN DE LA SOLUCIÓN**
- Se agregaron los métodos con los requerimientos solicitados, intentando en lo mas posible reutilizar el código existente 😌
- Se actualizó la documentación

2022-01-18 21:35 UTC, gastonpereyra commented on README.md
> +#### SERVICE-CALL
Sabes que le pondría el emoji de :new:  para hacerlo destacar ya que es como la nueva gran función.

2022-01-18 21:41 UTC, gastonpereyra commented on README.md
> +#### SERVICE-CALL
También para destacar esta parte las agruparia dentro de un nuevo titulo

```
### Service Invoker :children_crossing: 
The Invoker make *sync* invokes to a Lambda Function across different Services
```

Porque además estas invocaciones deberian ser Sync (esperan respuestas) y son a través de diferentes Servicios..

2022-01-18 22:17 UTC, gastonpereyra commented on lib/invoker.js
> +		const { StatusCode, FunctionError, Payload } = invokeResponse;
Porque no el destructuring en los parametros ?

2022-01-18 22:25 UTC, gastonpereyra commented on lib/secret-fetcher.js
> +		if(process.env.JANIS_ENV === 'local') {
Esto significa que en local no anda ?

2022-01-18 22:31 UTC, gastonpereyra commented on README.md
> +    * `functionName` (*string*) **required**, function name in TitleCase or dash-case
Estaria bueno aclarar de donde se va a sacar el function name para no estar probando y errando continuamente

2022-01-19 14:24 UTC, Nataniel4 commented on README.md
> +    * `functionName` (*string*) **required**, function name in TitleCase or dash-case
No entendí 🤔

2022-01-19 14:25 UTC, Nataniel4 commented on lib/secret-fetcher.js
> +		if(process.env.JANIS_ENV === 'local') {
Si 😭 en local no anda, igual lo agregue en la docu ahora 😌

2022-01-19 15:55 UTC, gastonpereyra commented on lib/secret-fetcher.js
> +		if(process.env.JANIS_ENV === 'local') {
MMMMMMMMMMMMMMMMMMMMMM...

Me parece que se podría..

En local puedo invocarlas desde
* Postman/Curl o similar
* Terminal via comandos

Las lambdas estan accesibles, mucho más fácil que en los ambientes. Y son todas Sync además.

Asi que debe haber forma de hacerlo, y creo que es necesario, porque sin esto muchos desarrollos son super-inviables en local, incluso cosas simples.

Mira:

![image](https://user-images.githubusercontent.com/39351850/150165492-fb9a3d34-470e-4b83-acff-33fb281712ab.png)

Esa es la modificación del Invoker normal para poder conectarse a lambdas.

Es super manual, y estoy seguro que cambiando el puerto podrias pegarle a cualquier lambda incluso fuera del servicio.

Porque no probas un poco a ver que sale?

Creo que como una primera etapa que sepa sacar el puerto en local y poder pegarle a la función solo si tenes el servicio levantado ya es re útil. Y más adelante se modificará el Mocking para que funcione con esto.

2022-01-28 20:18 UTC, gastonpereyra commented on lib/invoker.js
> +	static get isLocalEnv() {
Esto podria estar en `lambda-wrapper` y asi no pasarlo por parametro..

2022-01-28 21:15 UTC, gastonpereyra approved these changes

2022-01-31 19:08 UTC, juanhapes requested changes

2022-01-31 19:08 UTC, juanhapes commented on lib/invoker.js
> +	static async serviceSafeClientCall(serviceCode, functionName, session, body) {
Esta función está 99% repetida... por `serviceSafeCall()`
Propongo que esta funció llame a `serviceSafeCall()` que pueda recibir **como último** parámetro `session` para poder preguntar `if(session)` y no repetir código como loco

2022-01-31 19:08 UTC, juanhapes commented on lib/invoker.js
> +	static async serviceSafeClientCall(serviceCode, functionName, session, body) {
Y si eso sale bien... podríamos pensarlo seriamente también para `call` y `clientCall`

2022-01-31 19:43 UTC, Nataniel4 commented on README.md
> +    Invoke JanisKittyService-readme-AwakeKitties function without payload
Si, a mi tambien me parecio medio raro pero lo deje porque asi esta en los demas ejemplos, creo que lo que quiso significar fue el "ambiente" dentro del nombre formateado de la función:

Ejemplo: se envia functionName "AwakeKitties"

El package lo formatearía asi, suponiendo que estamos en el servicio Kitty y ambiente beta: "JanisKittyService-beta-AwakeKitties

Pero como es el readme se usó readme y yo no quise romper la armonia 😛 si queres lo cambio, nomas decime 😌

2022-02-02 21:02 UTC, merged